# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 14:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='', unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_reach.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileGreetedByActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLikedByActiveUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('bio', models.CharField(default='No description yet... this user must be shy!', max_length=500)),
                ('looking_for', models.CharField(choices=[('Girls', 'Girls'), ('Guys', 'Guys'), ('Any', 'Any')], max_length=6)),
                ('date_of_birth', models.DateField(default=datetime.datetime(2018, 10, 24, 14, 51, 11, 953860))),
                ('gender_identity', models.IntegerField(choices=[(-100, -100), (-99, -99), (-98, -98), (-97, -97), (-96, -96), (-95, -95), (-94, -94), (-93, -93), (-92, -92), (-91, -91), (-90, -90), (-89, -89), (-88, -88), (-87, -87), (-86, -86), (-85, -85), (-84, -84), (-83, -83), (-82, -82), (-81, -81), (-80, -80), (-79, -79), (-78, -78), (-77, -77), (-76, -76), (-75, -75), (-74, -74), (-73, -73), (-72, -72), (-71, -71), (-70, -70), (-69, -69), (-68, -68), (-67, -67), (-66, -66), (-65, -65), (-64, -64), (-63, -63), (-62, -62), (-61, -61), (-60, -60), (-59, -59), (-58, -58), (-57, -57), (-56, -56), (-55, -55), (-54, -54), (-53, -53), (-52, -52), (-51, -51), (-50, -50), (-49, -49), (-48, -48), (-47, -47), (-46, -46), (-45, -45), (-44, -44), (-43, -43), (-42, -42), (-41, -41), (-40, -40), (-39, -39), (-38, -38), (-37, -37), (-36, -36), (-35, -35), (-34, -34), (-33, -33), (-32, -32), (-31, -31), (-30, -30), (-29, -29), (-28, -28), (-27, -27), (-26, -26), (-25, -25), (-24, -24), (-23, -23), (-22, -22), (-21, -21), (-20, -20), (-19, -19), (-18, -18), (-17, -17), (-16, -16), (-15, -15), (-14, -14), (-13, -13), (-12, -12), (-11, -11), (-10, -10), (-9, -9), (-8, -8), (-7, -7), (-6, -6), (-5, -5), (-4, -4), (-3, -3), (-2, -2), (-1, -1), (0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (39, 39), (40, 40), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (49, 49), (50, 50), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (56, 56), (57, 57), (58, 58), (59, 59), (60, 60), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (66, 66), (67, 67), (68, 68), (69, 69), (70, 70), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (76, 76), (77, 77), (78, 78), (79, 79), (80, 80), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85), (86, 86), (87, 87), (88, 88), (89, 89), (90, 90), (91, 91), (92, 92), (93, 93), (94, 94), (95, 95), (96, 96), (97, 97), (98, 98), (99, 99)], default=0)),
                ('location', models.CharField(default='', max_length=128)),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('greetings', models.IntegerField(default=0)),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('picture_two', models.ImageField(blank=True, upload_to='profile_images')),
                ('picture_three', models.ImageField(blank=True, upload_to='profile_images')),
                ('picture_four', models.ImageField(blank=True, upload_to='profile_images')),
                ('picture_five', models.ImageField(blank=True, upload_to='profile_images')),
                ('picture_six', models.ImageField(blank=True, upload_to='profile_images')),
                ('instagram_handle', models.CharField(default='', max_length=128)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('twitter_handle', models.CharField(default='', max_length=128)),
                ('twitter_followers', models.IntegerField(default=0)),
                ('youtube_handle', models.CharField(default='', max_length=128)),
                ('youtube_followers', models.IntegerField(default=0)),
                ('ignored_profiles', models.ManyToManyField(blank=True, related_name='ignored_user', to=settings.AUTH_USER_MODEL)),
                ('liked_profiles', models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profilelikedbyactiveuser',
            name='liker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liker', to='social_reach.UserProfile'),
        ),
        migrations.AddField(
            model_name='profilegreetedbyactiveuser',
            name='greeter',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='greeter', to='social_reach.UserProfile'),
        ),
        migrations.AddField(
            model_name='match',
            name='first_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='first', to='social_reach.UserProfile'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='second', to='social_reach.UserProfile'),
        ),
    ]
