# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-24 16:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 24, 16, 47, 0, 402099)),
        ),
    ]
