# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-04 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0002_auto_20181003_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='first', to='social_reach.UserProfile')),
                ('second_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='second', to='social_reach.UserProfile')),
            ],
        ),
    ]
