# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-05 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0003_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='twitter_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
