# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0004_auto_20181005_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='youtube_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_handle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
