# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0004_auto_20181024_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 8, 46, 42, 196778)),
        ),
    ]
