# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0005_auto_20181006_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_followers',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
