# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0006_auto_20181006_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='youtube_followers',
            field=models.IntegerField(default=0),
        ),
    ]
