# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-25 15:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0007_auto_20181025_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 15, 17, 24, 55478)),
        ),
    ]
