# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0008_userprofile_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(choices=[('Both', 'Both'), ('Male', 'Male'), ('Female', 'Female')], default='', max_length=6),
        ),
    ]
