# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 18:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0010_auto_20181025_1823'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='gym',
            new_name='prefers_chill_to_gym',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 18, 38, 23, 504267)),
        ),
    ]
