# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 20:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0011_auto_20181025_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_age_desired',
            field=models.IntegerField(default=99),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_distance_acceptable',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='min_age_desired',
            field=models.IntegerField(default=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 25, 20, 29, 16, 297496)),
        ),
    ]
