# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0008_auto_20181025_1517'),
        ('social_reach', '0012_auto_20181025_2029'),
    ]

    operations = [
    ]
