# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 14:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0013_auto_20181010_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 15, 9, 48, 932000)),
        ),
    ]
