# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 14:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0014_auto_20181010_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 15, 11, 33, 23000)),
        ),
    ]
