# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0019_auto_20181010_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 16, 31, 29, 58890)),
        ),
    ]
