# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-10 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0020_auto_20181010_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 10, 16, 33, 41, 399274)),
        ),
    ]
