# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 10:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0031_auto_20181016_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 17, 10, 11, 31, 680211)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='looking_for',
            field=models.CharField(choices=[('Girls', 'Girls'), ('Guys', 'Guys'), ('Any', 'Any')], max_length=6),
        ),
    ]
