# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-18 12:41
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0034_auto_20181018_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 12, 41, 51, 331535)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_profiles',
            field=models.ManyToManyField(default=[], related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
