# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0035_auto_20181018_1529'),
        ('social_reach', '0036_auto_20181018_1307'),
    ]

    operations = [
    ]
