# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 15:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0036_auto_20181018_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 18, 15, 42, 50, 367794)),
        ),
    ]
