# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 13:48
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0037_merge_20181018_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 19, 13, 48, 37, 977206)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ignored_profiles',
            field=models.ManyToManyField(blank=True, related_name='ignored_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='liked_profiles',
            field=models.ManyToManyField(blank=True, related_name='liked_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
