# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-23 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0038_auto_20181019_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zeroth_picture',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2018, 10, 23, 13, 38, 26, 311481)),
        ),
    ]
