# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram',
            field=models.CharField(default='', max_length=128),
        ),
    ]
