# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_handle',
            field=models.CharField(default='', max_length=128),
        ),
    ]
