# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-03 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_reach', '0002_userprofile_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='instagram_followers',
            field=models.IntegerField(default=0),
        ),
    ]
